# Generated by Django 5.0.14 on 2026-06-19 04:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'medical_diagnosis',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, default='', max_length=20)),
                ('package', models.CharField(blank=True, default='', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('care_type', models.CharField(blank=True, default='', max_length=20)),
                ('frequency', models.IntegerField(default=1)),
                ('patient_category', models.IntegerField(default=15)),
            ],
            options={
                'db_table': 'medical_item',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, default='', max_length=20)),
                ('level', models.CharField(blank=True, default='', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('care_type', models.CharField(blank=True, default='', max_length=20)),
                ('frequency', models.IntegerField(default=1)),
                ('patient_category', models.IntegerField(default=15)),
            ],
            options={
                'db_table': 'medical_service',
                'ordering': ['code'],
            },
        ),
    ]
