# Generated by Django 5.0.14 on 2026-06-19 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'insuree_family_type',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'insuree_gender',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('relation', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'insuree_relation',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poverty', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location')),
                ('family_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insuree.familytype')),
            ],
            options={
                'db_table': 'insuree_family',
            },
        ),
        migrations.CreateModel(
            name='Insuree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chf_id', models.CharField(max_length=20, unique=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('other_names', models.CharField(blank=True, default='', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('head', models.BooleanField(default=False)),
                ('marital', models.CharField(blank=True, default='', max_length=10)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(blank=True, default='AC', max_length=10)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='insuree.family')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insuree.gender')),
            ],
            options={
                'db_table': 'insuree_insuree',
            },
        ),
        migrations.AddField(
            model_name='family',
            name='head_insuree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headed_families', to='insuree.insuree'),
        ),
        migrations.CreateModel(
            name='InsureePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('insuree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='insuree.insuree')),
            ],
            options={
                'db_table': 'insuree_insuree_policy',
            },
        ),
    ]
