# Generated by Django 5.0.14 on 2026-06-19 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insuree', '0001_initial'),
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insureepolicy',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insuree_policies', to='policy.policy'),
        ),
        migrations.AddField(
            model_name='insuree',
            name='relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insuree.relation'),
        ),
        migrations.AlterUniqueTogether(
            name='insureepolicy',
            unique_together={('insuree', 'policy')},
        ),
    ]
