# Generated by Django 5.0.14 on 2026-06-19 04:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('insurance_period', models.IntegerField(default=12)),
                ('administration_period', models.IntegerField(default=1)),
                ('lump_sum', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('max_members', models.IntegerField(default=10)),
                ('premium_adult', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('premium_child', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location')),
            ],
            options={
                'db_table': 'product_product',
            },
        ),
    ]
