// Auto-generated by openimis-config-vite.js
// Updated for Vite with local file dependencies
import { CoreModule } from "@openimis/fe-core";
import { HomeModule } from "@openimis/fe-home";
import { LocationModule } from "@openimis/fe-location";
import { InsureeModule } from "@openimis/fe-insuree";
import { MedicalModule } from "@openimis/fe-medical";
import { ClaimModule } from "@openimis/fe-claim";
import { PaymentGatewayModule } from "./custom/index";

export const packages = [
  "@openimis/fe-core",
  "@openimis/fe-home",
  "@openimis/fe-location",
  "@openimis/fe-insuree",
  "@openimis/fe-medical",
  "@openimis/fe-claim",
  "custom-payment-gateway",
];

export async function loadModules(cfg = {}) {
  const loadedModules = [];

  try {
    loadedModules.push(CoreModule(cfg["fe-core"] || {}));
  } catch (error) {
    console.error(`Failed to initialize module "CoreModule". Error: ${error}`);
    alert(`Failed to load module "CoreModule". See console for details.`);
  }

  try {
    loadedModules.push(HomeModule(cfg["fe-home"] || {}));
  } catch (error) {
    console.error(`Failed to initialize module "HomeModule". Error: ${error}`);
    alert(`Failed to load module "HomeModule". See console for details.`);
  }

  try {
    loadedModules.push(LocationModule(cfg["fe-location"] || {}));
  } catch (error) {
    console.error(`Failed to initialize module "LocationModule". Error: ${error}`);
    alert(`Failed to load module "LocationModule". See console for details.`);
  }

  try {
    loadedModules.push(InsureeModule(cfg["fe-insuree"] || {}));
  } catch (error) {
    console.error(`Failed to initialize module "InsureeModule". Error: ${error}`);
    alert(`Failed to load module "InsureeModule". See console for details.`);
  }

  try {
    loadedModules.push(MedicalModule(cfg["fe-medical"] || {}));
  } catch (error) {
    console.error(`Failed to initialize module "MedicalModule". Error: ${error}`);
    alert(`Failed to load module "MedicalModule". See console for details.`);
  }

  try {
    loadedModules.push(ClaimModule(cfg["fe-claim"] || {}));
  } catch (error) {
    console.error(`Failed to initialize module "ClaimModule". Error: ${error}`);
    alert(`Failed to load module "ClaimModule". See console for details.`);
  }

  try {
    loadedModules.push(PaymentGatewayModule(cfg["payment"] || {}));
  } catch (error) {
    console.error(`Failed to initialize module "PaymentGatewayModule". Error: ${error}`);
  }

  return loadedModules;
}
