# Generated by Django 5.0.14 on 2026-06-19 04:22

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('medical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qty_claimed', models.PositiveIntegerField(default=1)),
                ('price_claimed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('remunerated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'claim_app_claim_item',
            },
        ),
        migrations.CreateModel(
            name='ClaimService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qty_claimed', models.PositiveIntegerField(default=1)),
                ('price_claimed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('remunerated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'claim_app_claim_service',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ENTERED', 'Entered'), ('CHECKED', 'Checked'), ('PROCESSED', 'Processed'), ('VALUATED', 'Valuated'), ('REJECTED', 'Rejected')], default='ENTERED', max_length=20)),
                ('claimed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('remunerated', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.diagnosis')),
                ('health_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='location.healthfacility')),
            ],
            options={
                'db_table': 'claim_app_claim',
                'ordering': ['-created_at'],
            },
        ),
    ]
