# Generated by Django 5.0.14 on 2026-06-19 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claim_app', '0001_initial'),
        ('insuree', '0001_initial'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='insuree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insuree.insuree'),
        ),
        migrations.AddField(
            model_name='claimitem',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='claim_app.claim'),
        ),
        migrations.AddField(
            model_name='claimitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.item'),
        ),
        migrations.AddField(
            model_name='claimservice',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='claim_app.claim'),
        ),
        migrations.AddField(
            model_name='claimservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical.service'),
        ),
    ]
