# Generated by Django 5.0.14 on 2026-06-19 04:22

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claim_app', '0001_initial'),
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalPaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('batch_code', models.CharField(max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_claims', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('payment_api_reference', models.CharField(blank=True, default='', max_length=200)),
                ('payment_api_response', models.JSONField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_batches', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('health_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_batches', to='location.healthfacility')),
            ],
            options={
                'db_table': 'hospital_payment_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalPaymentBatchClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('claim_code', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=200)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='claim_app.claim')),
                ('payment_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_claims', to='hospital_payment.hospitalpaymentbatch')),
            ],
            options={
                'db_table': 'hospital_payment_batch_claim',
            },
        ),
        migrations.CreateModel(
            name='HospitalPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_api_reference', models.CharField(blank=True, default='', max_length=200)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('claims_paid_count', models.PositiveIntegerField(default=0)),
                ('claims_failed_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('received_date', models.DateTimeField()),
                ('payment_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='hospital_payment.hospitalpaymentbatch')),
            ],
            options={
                'db_table': 'hospital_payment_record',
                'ordering': ['-received_date'],
            },
        ),
    ]
